downstream_dependencies:
  - h1_hesc
  - mycoplasma_pneumoniae
  - rand_wc_model_gen
  - wc
  - wc_analysis
  - wc_model_gen
  - wc_test
email_notifications:
  - jonrkarr@gmail.com
  - balazs.szigeti@mssm.edu