downstream_dependencies:
  - h1_hesc
  - mycoplasma_pneumoniae
  - rand_wc_model_gen
  - wc_cli
  - wc_analysis
  - wc_kb_gen
  - wc_model_gen
  - wc_test
email_notifications:
  - jonrkarr@gmail.com
  - balazs.szigeti@mssm.edu
  - bilal.shaikh@columbia.edu