name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python>=3.6.4
  - sphinx
  #- openbabel
  - pip:
    - configparser
    - sphinx_rtd_theme
    - robpol86_sphinxcontrib_googleanalytics
    - sphinxcontrib_bibtex
    - sphinxcontrib_spelling
    - git+https://github.com/KarrLab/wc_utils.git
