name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python>=3.6.4
  - sphinx
  #- openbabel
  - pip:
    - biopython
    - enum34
    - git+https://github.com/KarrLab/obj_model.git#egg=obj_model
    - setuptools
    - git+https://github.com/KarrLab/wc_utils.git#egg=wc_utils

    - configparser
    - robpol86_sphinxcontrib_googleanalytics
    - six
    - sphinx_rtd_theme
    - sphinxcontrib_bibtex
    - sphinxcontrib_spelling
